baseURL = "https://dnegrey.com"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "dnegrey-blog"

# Google Analytics
googleAnalytics = "UA-69162453-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
title = "Dan Negrey"
author = "Dan Negrey"
description = "Data Scientist"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
customCss = ["css/styles.css"]
customJs = []
mainSections = ["blog"]
images = ["images/site-feature-image.png"]
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/dnegrey/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dnegrey"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/negreydan"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:dnegrey@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
